// Public copyable recipes, shared verbatim between the console and docs.
export const backends = ["Next.js", "FastAPI", "Express", "Plain HTTP"] as const;
export type Backend = (typeof backends)[number];
export const frontends = ["React", "Angular", "API only"] as const;
export type Frontend = (typeof frontends)[number];
export const hostContract = "Required host adapter (YOUR code, not a MindBill export):\nauthorizeBillingSession(request) must authenticate the signed-in user, enforce the\nbilling feature flag and role, and resolve their active customer using SERVER-owned\nsession/membership data. Return { subject, apiKey, permissions, resource? }.\nDeny unauthenticated/unauthorized requests with your framework's 401/403 response.\n\nSelect apiKey from your secret-manager mapping for that customer's MindBill organization.\nNever accept API keys, tenant/org IDs, subjects, permissions or allowedOrigin from clients.\nsubject is audit identity, NOT tenant isolation. Organization-scoped sessions can access\nall bills in that organization; never share them across unrelated customers.\n\nFull workspace: bills:create, bills:read, bills:act, documents:read, payers:read, eors:read.\nRead-only roles: bills:read, documents:read, payers:read, eors:read.\nCase-only endpoint: authorize the host case and resolve its saved bill ID server-side,\nset resource: { billId }, and omit bills:create.\nSeparate admin-only settings endpoint: organization:manage. Never grant this to all billers.\n\nAPP_ORIGIN is your FRONTEND origin (scheme + host + port, no path/trailing slash), not\nthe API server URL. Sandbox: http://localhost:3000; live: https://app.example.com.\nFor multiple frontend origins, validate against a server allowlist; never reflect Origin.\nFor split frontend/backend hosts, add exact-origin credentialed CORS, existing CSRF\nprotection, and a getSession callback with credentials: \"include\" where required.\nKeep the host adapter fail-closed until connected to real authentication.";
const jsHelper = "// Server only. Replace this placeholder with your EXISTING auth/tenant/role checks.\nasync function authorizeBillingSession(_request) {\n  throw new Error(\"Connect existing authentication and customer-key mapping first\");\n}\n\nasync function mintSession(access) {\n  const response = await fetch(\"https://app.mindbill.org/partner/v2/browser-sessions\", {\n    method: \"POST\",\n    headers: { Authorization: \"Bearer \" + access.apiKey, \"Content-Type\": \"application/json\" },\n    body: JSON.stringify({\n      subject: access.subject, allowedOrigin: process.env.APP_ORIGIN,\n      permissions: access.permissions,\n      ...(access.resource ? { resource: access.resource } : {}),\n      expiresIn: 900,\n    }),\n    signal: AbortSignal.timeout(10000),\n    cache: \"no-store\",\n  });\n  if (!response.ok) throw new Error(\"Unable to start billing session\");\n  return response.json();\n}";
export const serverRecipes: Record<Backend, string> = {
"Next.js": "// app/api/mindbill/session/route.js (App Router)\nexport async function POST(request) {\n  if (!process.env.APP_ORIGIN || request.headers.get(\"origin\") !== process.env.APP_ORIGIN)\n    return Response.json({ error: \"Origin not allowed\" }, { status: 403 });\n  try {\n    const access = await authorizeBillingSession(request);\n    return Response.json(await mintSession(access), { headers: { \"Cache-Control\": \"no-store\" } });\n  } catch {\n    // Map your adapter's auth failures to 401/403; never forward upstream bodies.\n    return Response.json({ error: \"Billing session unavailable\" }, { status: 503 });\n  }\n}\n\n" + jsHelper,
Express: "// Existing Express server; browser uses same-origin /api/mindbill/session.\napp.post(\"/api/mindbill/session\", async (req, res) => {\n  if (!process.env.APP_ORIGIN || req.get(\"origin\") !== process.env.APP_ORIGIN)\n    return res.status(403).json({ error: \"Origin not allowed\" });\n  try {\n    const access = await authorizeBillingSession(req);\n    res.set(\"Cache-Control\", \"no-store\").json(await mintSession(access));\n  } catch {\n    // Map host auth failures to 401/403; do not expose upstream response bodies.\n    res.status(503).json({ error: \"Billing session unavailable\" });\n  }\n});\n\n" + jsHelper,
FastAPI: "# Existing FastAPI app. Dependency: requests.\nimport os\nimport requests\nfrom fastapi import Request, HTTPException\nfrom fastapi.responses import JSONResponse\n\ndef authorize_billing_session(request):\n    # Implement the required host adapter above. Fail closed until wired.\n    raise HTTPException(503, \"Connect existing authentication and customer-key mapping first\")\n\n@app.post(\"/api/mindbill/session\")\ndef create_billing_session(request: Request):\n    origin = os.environ.get(\"APP_ORIGIN\")\n    if not origin or request.headers.get(\"origin\") != origin:\n        raise HTTPException(403, \"Origin not allowed\")\n    access = authorize_billing_session(request)\n    payload = {\n        \"subject\": access[\"subject\"], \"allowedOrigin\": origin,\n        \"permissions\": access[\"permissions\"], \"expiresIn\": 900,\n    }\n    if access.get(\"resource\"):\n        payload[\"resource\"] = access[\"resource\"]\n    try:\n        upstream = requests.post(\n            \"https://app.mindbill.org/partner/v2/browser-sessions\",\n            headers={\"Authorization\": \"Bearer \" + access[\"apiKey\"]},\n            json=payload, timeout=10,\n        )\n        upstream.raise_for_status()\n        data = upstream.json()\n    except (requests.RequestException, ValueError):\n        raise HTTPException(502, \"Unable to start billing session\") from None\n    return JSONResponse(data, headers={\"Cache-Control\": \"no-store\"})",
"Plain HTTP": "# Server-to-server ONLY, after host authentication, role and tenant checks.\nPOST https://app.mindbill.org/partner/v2/browser-sessions\nAuthorization: Bearer <server-only-sandbox-key>\nContent-Type: application/json\n\n{\n  \"subject\": \"<authenticated-user-id>\",\n  \"allowedOrigin\": \"http://localhost:3000\",\n  \"permissions\": [\"bills:create\", \"bills:read\", \"bills:act\", \"documents:read\", \"payers:read\", \"eors:read\"],\n  \"expiresIn\": 900\n}\n\n# Return successful JSON with Cache-Control: no-store to that authenticated user.\n# Reject invalid origins/unauthorized requests BEFORE calling MindBill.\n# On failure return a generic error, never upstream response bodies.\n# API-only: call bill endpoints server-to-server instead of minting browser tokens.\n# https://docs.mindbill.org/api-reference/create-bill"
};
export const reactRecipe = "\"use client\";\nimport {\n  ConnectedBillingWorkspace, ConnectedBillLifecycle,\n  BillSubmissionForm, BillingSettings,\n} from \"@mindbill/react\";\nimport \"@mindbill/react/styles.css\";\n\n// Sidebar -> /billing. The workspace owns bill selection and detail navigation.\nexport function BillingPage() {\n  return <ConnectedBillingWorkspace\n    sessionEndpoint=\"/api/mindbill/session\"\n    style={{ height: \"calc(100dvh - 96px)\", minHeight: 0 }}\n    onCreateBill={() => { window.location.href = \"/billing/new\"; }}\n  />;\n}\n\n// Case -> Billing tab after Report. Host server authorizes the case and resolves\n// its saved bill ID; return a bill-scoped session from this separate host route.\nexport function CaseBilling({ caseId, billId }) {\n  return <ConnectedBillLifecycle billId={billId}\n    sessionEndpoint={\"/api/cases/\" + encodeURIComponent(caseId) + \"/billing-session\"} />;\n}\n\n// Map existing structured case data to BillSubmissionInput, persist result.billId\n// using your existing case metadata/API, and keep unknown fields editable.\nexport function NewBill({ initialBill, finalizedReportAttachments, onSubmitted }) {\n  return <BillSubmissionForm initialBill={initialBill}\n    attachments={finalizedReportAttachments}\n    sessionEndpoint=\"/api/mindbill/session\" onSubmitted={onSubmitted} />;\n}\n\n// Settings -> Billing. Separate admin-only endpoint grants organization:manage.\nexport function PracticeBillingSettings() {\n  return <BillingSettings sessionEndpoint=\"/api/mindbill/settings-session\" />;\n}";
export const implementationChecklist = "Inspect the existing app first. Do not replace authentication or run a migration.\n1. Gate sidebar Billing, case Billing tab and server endpoints with the EXISTING tenant/user\n   feature flag. Verify enrolled users see both entries and others see neither.\n2. Render ConnectedBillingWorkspace in a bounded, shrinkable layout. Import the CSS once.\n   Case Billing: creation form until submitted, then lifecycle. Settings: admin-only.\n3. Implement the selected server recipe AND host auth adapter using server-owned tenant\n   mapping. Browser sees short-lived tokens only. Never hardcode a subject or API key.\n4. Reuse existing case metadata for externalId and returned billId. externalId is correlation,\n   not an idempotency/uniqueness guarantee. Never recreate a bill on rerender.\n   Avoid local copies of bills/payments/EORs. If no durable mapping exists, explain the\n   smallest necessary persistence change first; do not run a speculative migration.\n5. Prefill known patient/address/injury/claim/service/diagnosis/code/modifier values from\n   structured host data. Leave unknown fields editable; never fabricate clinical values.\n   Do not add regex/AI report parsing during SDK setup. Use existing extraction and user\n   review. Confirm the canonical payer directory choice before submission.\n6. Autoattach ONLY the finalized report, not every case document, medical record or audio\n   file. Let users upload/select proof of service and additional supporting PDFs.\n7. Decide data ownership: host-managed providers/locations/W-9 OR MindBill BillingSettings.\n   Avoid duplicated storage and silently copying sensitive tax identifiers.\n8. Keep API keys/tokens/SSN/tax IDs/PHI out of logs, localStorage and coding-agent prompts.\n9. Verify sandbox Sent -> Accepted/Rejected -> Processed, second review/routing, payments,\n   notes, attachments, All Bills visibility and laptop/mobile scrolling. Sent bills waiting\n   for payers are not follow-up tasks but MUST remain discoverable.\n10. For notifications, verify webhook raw-body signatures, deduplicate event IDs, tolerate\n    retries/out-of-order delivery and reconcile authoritative state. Keep notification\n    email PHI-free with authenticated links. https://docs.mindbill.org/api-reference/events\n11. Test token refresh, 401/403, cross-tenant IDs, disabled feature flags, non-admin settings,\n    missing origin config, empty/error states. Keep sandbox and live keys/data separate.\n12. Run typecheck/build/tests; report changed files, actual package versions and unfinished\n    host adapters. An unwired auth placeholder is NOT a finished integration.";
export const prefillRecipe = "// Host adapter example: rename these source fields to your existing structured data.\n// Do not infer clinical codes or upload every case document during SDK setup.\nexport function billFromCase(caseRecord) {\n  return {\n    externalId: String(caseRecord.id),\n    patient: {\n      firstName: caseRecord.patient.firstName ?? \"\",\n      lastName: caseRecord.patient.lastName ?? \"\",\n      dateOfBirth: caseRecord.patient.dateOfBirth ?? \"\", // YYYY-MM-DD\n      address: {\n        line1: caseRecord.patient.address?.line1 ?? \"\",\n        city: caseRecord.patient.address?.city ?? \"\",\n        state: caseRecord.patient.address?.state ?? \"\",\n        postalCode: caseRecord.patient.address?.postalCode ?? \"\",\n      },\n    },\n    claim: {\n      claimNumber: caseRecord.claimNumber ?? \"\",\n      employer: caseRecord.employerName,\n      dateOfInjury: caseRecord.dateOfInjury,\n    },\n    service: { date: caseRecord.dateOfService ?? \"\" },\n    diagnoses: caseRecord.diagnosisCodes ?? [],\n    serviceLines: (caseRecord.billingLines ?? []).map((line) => ({\n      code: line.code, modifiers: line.modifiers, units: line.units,\n    })),\n    // Optional: billingProvider, renderingProvider, serviceLocation from\n    // your saved host settings. Otherwise let the user supply/review them.\n  };\n}\n\n// Only pass the finalized report. An empty list leaves upload to the user.\n// documentId identifies a HOST document, not a MindBill document.\nexport function finalReportSources(documentId) {\n  if (!documentId) return [];\n  return [{\n    id: documentId, fileName: \"final-report.pdf\",\n    documentType: \"final_report\", autoAttached: true, removable: true,\n    loadBlob: async () => {\n      // Existing authenticated host endpoint: enforce document/case ownership.\n      const response = await fetch(\"/api/documents/\" + encodeURIComponent(documentId), {\n        credentials: \"same-origin\", cache: \"no-store\",\n      });\n      if (!response.ok) throw new Error(\"Unable to load finalized report\");\n      return response.blob();\n    },\n  }];\n}";

export const profileRecipe = `// Requires @mindbill/react >=0.47.0 and @mindbill/browser >=0.28.0.
// MindBill-managed profile lookup:
// GET /partner/v2/browser/organization/billing-profile
// Use an authenticated organization-wide browser session with bills:create.
// A bill-scoped session cannot read organization-wide profile choices.
// Settings writes still need an ADMIN-authorized organization:manage session.
"use client";
import { useEffect, useState } from "react";
import { createOrganizationClient } from "@mindbill/browser";
import { BillSubmissionForm, organizationProfileOptions } from "@mindbill/react";

export function ProfileBasedBill({ initialBill }) {
  const [profile, setProfile] = useState(null);
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    let active = true;
    const client = createOrganizationClient({ sessionEndpoint: "/api/mindbill/session" });
    client.getBillingProfile().then(
      (value) => { if (active) setProfile(value); },
      () => { if (active) setFailed(true); },
    );
    return () => { active = false; };
  }, []);
  if (failed) return <p role="alert">Unable to load billing profiles. Please try again.</p>;
  if (!profile) return <p role="status">Loading billing profiles…</p>;
  return <BillSubmissionForm initialBill={initialBill}
    sessionEndpoint="/api/mindbill/session"
    profileOptions={organizationProfileOptions(profile)}
    profileDisplay="compact" />;
}

// getBillingProfile() returns masked OrganizationProfileData, not the { data } envelope.
// getOrganization() is the separate admin-only settings read; do not grant admin
// permission to ordinary bill creators just to populate these choices.
// SSN-backed choices retain a savedProviderId; the server resolves the SSN.
// Never put taxIdLast4 in taxId, browser storage, telemetry or agent prompts.
// Host-managed alternative: pass your OWN saved choices; no MindBill storage needed.
export function HostProfileBill({ initialBill, savedBillingProvider,
  savedRenderingProvider, savedServiceLocation }) {
  const profileOptions = {
    billingProviders: [{ id: "practice-1", label: "Main practice", value: savedBillingProvider }],
    renderingProviders: [{ id: "doctor-1", label: "Rendering doctor", value: savedRenderingProvider }],
    serviceLocations: [{ id: "office-1", label: "Main office", value: savedServiceLocation }],
  };
  return <BillSubmissionForm initialBill={initialBill} profileOptions={profileOptions}
    profileDisplay="compact" sessionEndpoint="/api/mindbill/session" />;
}
// Omit profileDisplay (or use "expanded") to show all fields.
// Selecting a profile does not mutate the saved profile.
// Settings supports taxIdType: "EIN" | "SSN" (default EIN).
// Saved SSNs are encrypted. Responses contain empty taxId, taxIdLast4 and
// taxIdConfigured. In settings: blank preserves, replacement changes, clear removes.
// Custom settings API writes: omit taxId to preserve; taxId: "" explicitly clears.
// Do not send response-only taxIdLast4/taxIdConfigured in a settings write.`;

export function integrationPacket(frontend: Frontend, backend: Backend) {
  const client = frontend === "React" ? reactRecipe : frontend === "Angular"
    ? "Use https://docs.mindbill.org/components/angular. Do not paste React JSX into Angular. Reuse the server-owned session boundary."
    : "Use server-only REST APIs: https://docs.mindbill.org/api-reference/create-bill. No React package or browser token required.";
  return ["# MindBill implementation brief", "Frontend: " + frontend + "; backend: " + backend,
    "Docs: https://docs.mindbill.org/learn/quickstart", "Sandbox key: https://platform.mindbill.org/settings/api-keys",
    frontend === "React" ? "Install: pnpm add @mindbill/react@latest" : "", hostContract, client,
    frontend === "API only" ? serverRecipes["Plain HTTP"] : serverRecipes[backend], prefillRecipe,
    frontend === "React" ? profileRecipe : "", implementationChecklist
  ].filter(Boolean).join("\n\n");
}
