export const apiHelper = "// Server-side helper for endpoints not yet wrapped by the Node SDK.\nexport async function api(path: string, method = \"GET\", body?: unknown, key?: string) {\n  const response = await fetch(`https://app.mindbill.org/partner/v2${path}`, {\n    method,\n    headers: {\n      Authorization: `Bearer ${process.env.MINDBILL_API_KEY}`,\n      ...(body === undefined ? {} : { \"Content-Type\": \"application/json\" }),\n      ...(key ? { \"Idempotency-Key\": key } : {}),\n    },\n    ...(body === undefined ? {} : { body: JSON.stringify(body) }),\n  });\n  if (!response.ok) throw new Error(`MindBill request failed: ${response.status}`);\n  return response.json();\n}";

export const apiInit = "import { MindBillClient } from \"@mindbill/node\";\n\nexport const mindbill = new MindBillClient({\n  apiKey: process.env.MINDBILL_API_KEY!,\n});";

export const apiCreate = "import { readFile } from \"node:fs/promises\";\nimport { mindbill } from \"./mindbill\";\n\nconst billInput = JSON.parse(await readFile(\"./bill.json\", \"utf8\"));\nconst report = await readFile(\"./synthetic-final-report.pdf\");\n\nconst bill = await mindbill.createAndSubmitBill({\n  bill: billInput,\n  submission: { route: \"ebill\" },\n  documents: [{\n    filename: \"synthetic-final-report.pdf\",\n    documentType: \"final_report\",\n    contentBase64: report.toString(\"base64\"),\n  }],\n}, \"demo-create-report-001\");\n\nconsole.log(bill.id);";

export const apiDirectory = "import { api } from \"./mindbill-api\";\n\nconst directory = await api(\"/claims-administrators?q=Sedgwick&limit=20\");\nconsole.log(directory.results);\n// Review the matching administrator and its payer options.\n// Set bill.json \u2192 claim.claimsAdministrator to its id and name.";

export const apiEams = "const savedClaim = await api(\"/claims\", \"POST\", {\n  patient: { ...billInput.patient, externalId: \"patient_demo_001\" },\n  claim: { ...billInput.claim, externalId: \"claim_demo_001\", adjNumber: \"ADJ1234567\" },\n}, \"demo-provision-claim-001\");\nconst preflight = await api(\n  `/claims/${encodeURIComponent(savedClaim.claimId)}/eams-preflight`, \"POST\", {},\n);\nconsole.log(preflight.status, preflight.candidates);\n// Review candidate claims administrators before choosing bill.claim.claimsAdministrator.";

export const apiStatus = "const status = await mindbill.getBillStatus(bill.id);\nconsole.log(status);\n\n// Full bill details and the actions currently available:\nconst currentBill = await mindbill.getBill(bill.id);\nconst lifecycle = await mindbill.getBillLifecycle(bill.id);";

export const apiClose = "await mindbill.performBillAction(bill.id, {\n  action: \"close\", reason: \"No further collection is needed.\",\n}, \"demo-close-001\");";

export const apiReopen = "await mindbill.performBillAction(bill.id, {\n  action: \"reopen\", reason: \"A new payment review is needed.\",\n}, \"demo-reopen-001\");";

export const apiNote = "import { api } from \"./mindbill-api\";\n\nawait api(`/bills/${encodeURIComponent(bill.id)}/actions`, \"POST\", {\n  action: \"add_note\", note: \"Requested an updated explanation of review.\",\n}, \"demo-note-001\");";

export const apiResubmit = "import { api } from \"./mindbill-api\";\n\nawait api(`/bills/${encodeURIComponent(bill.id)}/actions`, \"POST\", {\n  action: \"resubmit\", reason: \"Corrected the claim number.\",\n  bill: { ...billInput, claim: { ...billInput.claim, claimNumber: \"DEMO-12345-CORRECTED\" } },\n  submission: { route: \"ebill\" },\n}, \"demo-resubmit-001\");";

export const apiSecondReview = "import { api } from \"./mindbill-api\";\n\nawait api(`/bills/${encodeURIComponent(bill.id)}/actions`, \"POST\", {\n  action: \"second_review\",\n  lineItems: [{ lineItemId: \"YOUR_DISPUTED_LINE_ITEM_ID\", reason: \"Please review the denied service against the attached report.\" }],\n  route: \"ebill\",\n}, \"demo-second-review-001\");";

export const apiSearch = "import { api } from \"./mindbill-api\";\n\nconst dashboard = await api(\n  \"/bill-dashboard?status=denied,rejected&q=Example&page=1&pageSize=25&sort=balanceDue&dir=desc\",\n);\nconsole.log(dashboard.data.items, dashboard.data.total, dashboard.data.balanceTotal);";

export const apiList = "// Cursor list is for synchronization/iteration, not dashboard free-text search.\nconst page = await mindbill.listBills({ limit: 100 });\nif (page.nextCursor) {\n  const nextPage = await mindbill.listBills({ limit: 100, cursor: page.nextCursor });\n}";

export const apiProfile = "import { api } from \"./mindbill-api\";\n\nconst profile = await api(\"/organization/billing-profile\", \"PUT\", {\n  billingProviders: [{\n    externalId: \"practice_demo_001\",\n    name: \"Example Evaluations Medical Group, Inc.\",\n    taxId: \"12-3456789\", npi: \"1234567893\", billType: \"Professional\",\n    phone: \"213-555-0100\", billingStreet: \"100 Example Avenue\",\n    billingCity: \"Los Angeles\", billingState: \"CA\", billingZip: \"90012\",\n  }],\n}, \"demo-save-provider-001\");\nconst provider = profile.data.billingProviders.find(\n  (item: { externalId?: string }) => item.externalId === \"practice_demo_001\",\n);\nif (!provider) throw new Error(\"Saved provider was not returned.\");\nconst nextBillInput = { ...billInput, billingProvider: { savedProviderId: provider.id } };";

export const angularDashboardLoader = "import type { MindBillDashboardBill } from \"@mindbill/angular\";\n\ntype BrowserSession = { token: string; apiBaseUrl?: string };\ntype DashboardItem = {\n  id: string; billNumber?: string | number; patientName: string;\n  claimNumber?: string; claimsAdministrator?: string;\n  status: { key: string }; submittedAt?: string | null; arAgeDays?: number | null;\n  totalCharge: number; totalPaid: number; balanceDue: number;\n};\n\nexport async function loadDashboardBills(): Promise<MindBillDashboardBill[]> {\n  async function getSession(): Promise<BrowserSession> {\n    const response = await fetch(\"/api/mindbill/session\", {\n      method: \"POST\", credentials: \"same-origin\",\n      headers: { \"Content-Type\": \"application/json\" }, body: \"{}\",\n    });\n    if (!response.ok) throw new Error(\"Could not start billing session.\");\n    return response.json();\n  }\n  let session = await getSession();\n  const items: DashboardItem[] = [];\n  for (let page = 1; ; page++) {\n    const request = () => fetch(\n      `${(session.apiBaseUrl ?? \"https://app.mindbill.org\").replace(/\\/$/, \"\")}/partner/v2/bill-dashboard?page=${page}&pageSize=100`,\n      { headers: { Authorization: `Bearer ${session.token}` } },\n    );\n    let response = await request();\n    if (response.status === 401) { session = await getSession(); response = await request(); }\n    if (!response.ok) throw new Error(\"Could not load bills.\");\n    const { data } = await response.json() as {\n      data: { items: DashboardItem[]; total: number; page: number; pageSize: number };\n    };\n    items.push(...data.items);\n    if (data.page * data.pageSize >= data.total) break;\n    if (!data.items.length) throw new Error(\"Bill pagination did not finish.\");\n  }\n  return items.map((item) => ({\n    id: item.id, billNumber: item.billNumber, patientName: item.patientName,\n    claimNumber: item.claimNumber, payerName: item.claimsAdministrator,\n    state: item.status.key, submittedAt: item.submittedAt ?? undefined,\n    agingDays: item.arAgeDays ?? undefined,\n    totalCharge: item.totalCharge, totalPaid: item.totalPaid, balanceDue: item.balanceDue,\n  }));\n}";

export const exampleBill = "{\n  \"externalId\": \"report_demo_001\",\n  \"billingMode\": \"med_legal\",\n  \"patient\": {\n    \"firstName\": \"Taylor\",\n    \"lastName\": \"Example\",\n    \"dateOfBirth\": \"1984-04-12\",\n    \"address\": {\n      \"line1\": \"100 Example Avenue\",\n      \"city\": \"Los Angeles\",\n      \"state\": \"CA\",\n      \"postalCode\": \"90012\"\n    }\n  },\n  \"claim\": {\n    \"claimNumber\": \"DEMO-12345\",\n    \"employer\": \"Example Manufacturing\",\n    \"dateOfInjury\": \"2026-06-20\",\n    \"injuryState\": \"CA\",\n    \"claimsAdministrator\": {\n      \"id\": \"REPLACE_WITH_DIRECTORY_ID\",\n      \"name\": \"REPLACE_WITH_DIRECTORY_NAME\"\n    }\n  },\n  \"service\": {\n    \"date\": \"2026-08-25\"\n  },\n  \"billingProvider\": {\n    \"name\": \"Example Evaluations Medical Group, Inc.\",\n    \"taxId\": \"12-3456789\",\n    \"npi\": \"1234567893\",\n    \"phone\": \"213-555-0100\",\n    \"address\": {\n      \"line1\": \"100 Example Avenue\",\n      \"city\": \"Los Angeles\",\n      \"state\": \"CA\",\n      \"postalCode\": \"90012\"\n    }\n  },\n  \"renderingProvider\": {\n    \"name\": \"Avery Example, MD\",\n    \"npi\": \"1234567893\",\n    \"taxonomy\": \"208D00000X\"\n  },\n  \"serviceLocation\": {\n    \"name\": \"Main office\",\n    \"address\": {\n      \"line1\": \"100 Example Avenue\",\n      \"city\": \"Los Angeles\",\n      \"state\": \"CA\",\n      \"postalCode\": \"90012\"\n    },\n    \"placeOfServiceCode\": \"11\"\n  },\n  \"diagnoses\": [\n    \"M25.512\"\n  ],\n  \"serviceLines\": [\n    {\n      \"code\": \"ML201\",\n      \"units\": 1\n    }\n  ]\n}";
