import type { ApiEndpoint, ApiField } from "./api-reference";

const field = (name: string, type: string, description: string, required = false): ApiField => ({ name, type, description, required });
const json = (value: unknown) => JSON.stringify(value, null, 2);
const browserNotes = [{
  title: "Browser session required",
  body: "Mint a short-lived session through POST /partner/v2/browser-sessions with payers:read and an allowed origin. Send its token as Authorization: Bearer and the exact matching Origin header. These /browser routes do not accept a server API key. The React components use the same routes through @mindbill/browser.",
}];
const example = (path: string) => [{
  label: "cURL", language: "bash", filename: "Browser session request",
  code: `curl 'https://app.mindbill.org/partner/v2/browser/${path}' \\\n  --header "Authorization: Bearer $MINDBILL_BROWSER_TOKEN" \\\n  --header 'Origin: https://your-app.example'`,
}];

export const referenceDataEndpoints: ApiEndpoint[] = [
  {
    slug: "claims-administrators", group: "Directories", method: "GET",
    path: "/browser/claims-administrators", authentication: "browser-session",
    title: "Search claims administrators",
    summary: "Browse the payer directory or search administrators and payer choices before a bill exists.",
    useWhen: "Populate the claims-administrator selector in your own bill-entry form. listClaimsAdministrators() and searchClaimsAdministrators() call this endpoint; the SDK normalizes the raw directory response for the React components.",
    permissions: ["payers:read"],
    queryFields: [
      field("q", "string", "Administrator name search. Omit or leave blank to browse the directory."),
      field("claimNumber", "string", "Optional claim number used for matching hints."),
      field("sourceClaimsAdministratorName", "string", "Administrator name from the source record, used to rank matches."),
      field("employerName", "string", "Optional employer context for recommendations."),
      field("limit", "integer", "Page size; default 50, clamped to 1–100."),
      field("offset", "integer", "Zero-based offset; default 0."),
    ],
    responseFields: [
      field("results[]", "object[]", "Ranked directory entries for this page. The response is top-level, without a data wrapper."),
      field("results[].id", "string", "Opaque directory identifier. Send as claim.claimsAdministrator.id."),
      field("results[].name", "string", "Canonical display name. Send as claim.claimsAdministrator.name."),
      field("results[].hasElectronic", "boolean", "Whether the directory entry has electronic delivery support."),
      field("results[].states", "string[]", "States associated with the directory entry."),
      field("results[].confidence", '"high" | "medium" | "directory"', "Match confidence."),
      field("results[].recommended", "boolean", "Whether this entry is recommended for the supplied context."),
      field("results[].signals[]", "object[]", "Matching hints with kind (name or claim_number), state (match or warning), and label."),
      field("results[].payers[]", "object[]", "Payer choices with key, label, default, active, and optional affiliatedEntities and claimNumberPatterns."),
      field("results[].payers[].key", "string", "Opaque payer-choice key. The SDK exposes this as a payer id; send it as claim.claimsAdministrator.payerId."),
      field("results[].payerSelectionRequired", "boolean", "Whether a payer choice is needed within this administrator."),
      field("results[].aliases / affiliatedEntities", "string[]", "Optional alternate names and affiliated entities."),
      field("results[].claimNumberPatterns[]", "object[]", "Patterns with pattern, optional length/example, and matches (boolean or null when no claim number was supplied or the pattern cannot be evaluated)."),
      field("recommendedId", "string | null", "Exact-match recommendation, or null. Recommendations do not replace user review."),
      field("suggestions[]", "object[]", "Suggested directory entries with deterministic, reason, and optional selectedPayerId."),
      field("total", "integer", "Total matching entries before pagination."),
      field("nextOffset", "integer", "Offset for the next page; omitted on the last page."),
    ],
    examples: example("claims-administrators?q=Example&limit=20"),
    responseExample: json({ results: [{ id: "admin_example", name: "Example Claims Administrator", hasElectronic: false, states: ["CA"], confidence: "directory", recommended: false, signals: [], payers: [{ key: "payer_example", label: "Example Insurance", default: true, active: true }], payerSelectionRequired: false, claimNumberPatterns: [] }], recommendedId: null, suggestions: [], total: 1 }),
    notes: [...browserNotes, { title: "Keep the two identifiers separate", body: "The administrator id identifies the directory entry; payers[].key identifies a payer choice within it. Use the search result key for claim.claimsAdministrator.payerId, not a clearinghouse payer ID from the detail profile." }],
  },
  {
    slug: "claims-administrator", group: "Directories", method: "GET",
    path: "/browser/claims-administrators/{id}", authentication: "browser-session",
    title: "Get a claims administrator",
    summary: "Read an administrator's contact information, submission instructions, and payer metadata.",
    useWhen: "Display the directory detail panel after selecting an administrator. getClaimsAdministratorDirectory() calls this endpoint and unwraps data.",
    permissions: ["payers:read"],
    pathFields: [field("id", "string", "Directory identifier from the claims-administrator search results.", true)],
    queryFields: [field("injuryState", "string", "State used for directory information; default CA.")],
    responseFields: [
      field("data", "object", "Directory profile. Optional properties are omitted when information is unavailable."),
      field("data.id / name", "string", "Directory identifier and canonical name."),
      field("data.type / description / website / hours", "string", "Optional administrator profile information."),
      field("data.aliases / affiliatedEntities", "string[]", "Optional alternate names and related entities."),
      field("data.telephoneNumbers / emailAddresses / webPortals", "string[]", "Contact lists; may be empty."),
      field("data.claimNumberHint / billProcessingWorkflow / billProcessingWorkflowNotes", "string", "Optional claim-number and submission instructions."),
      field("data.payers[]", "object[]", "Optional payer metadata: name, route, aliases, hint, affiliatedEntities, optionType, deliveryType, clearinghouse, payerId, clearinghousePayerIds, and preferredClearinghouse."),
      field("data.authorizationNotice", "string", "Optional authorization notice."),
      field("data.billReview[] / authorization[]", "object[]", "Optional contacts with name, phone, fax, email, address, portalUrl, and note."),
      field("data.mailingAddresses[]", "object[]", "Mailing destinations with address and optional company, notes, billTreatmentTypes, and submissionTypes."),
      field("data.claimNumberPatterns[]", "object[]", "Claim-number patterns with pattern and optional length and example."),
    ],
    examples: example("claims-administrators/admin_example?injuryState=CA"),
    responseExample: json({ data: { id: "admin_example", name: "Example Claims Administrator", telephoneNumbers: [], emailAddresses: ["billing@example.com"], webPortals: [] } }),
    notes: [...browserNotes, { title: "Not found", body: 'An unknown directory identifier returns HTTP 404 with { "error": "claims_administrator_not_found" }.' }],
  },
  {
    slug: "diagnosis-codes", group: "Directories", method: "GET",
    path: "/browser/diagnosis-codes", authentication: "browser-session",
    title: "Search diagnosis codes",
    summary: "Look up ICD-10-CM codes by code prefix or description.",
    useWhen: "Populate the diagnosis selector in a bill-entry form. searchDiagnosisCodes() calls this endpoint.",
    permissions: ["payers:read"],
    queryFields: [field("q", "string", "Code or description search; blank browses the catalog."), field("limit", "integer", "Page size; default 30, clamped to 1–100."), field("offset", "integer", "Zero-based offset; default 0.")],
    responseFields: [field("results[]", "object[]", "This page's matches, each with code and description. No data wrapper."), field("total", "integer", "Full catalog size, not the number matching the query."), field("matched", "integer", "Number of matches available for the query before pagination."), field("error", "string", "Present when the code set is unavailable; see the error note.")],
    examples: example("diagnosis-codes?q=M25.562&limit=1"),
    responseExample: '{\n  "results": [{ "code": "M25.562", "description": "Pain in left knee" }],\n  "total": 100000,\n  "matched": 1\n}',
    notes: [...browserNotes, { title: "Catalog availability", body: 'If the code set cannot be loaded, this endpoint currently returns HTTP 200 with { "results": [], "total": 0, "error": "code set unavailable" }, without matched. Check error as well as HTTP status. The success example uses an illustrative catalog count.' }],
  },
  {
    slug: "postal-codes", group: "Directories", method: "GET",
    path: "/browser/postal-codes", authentication: "browser-session",
    title: "Look up a postal code",
    summary: "Resolve a US ZIP code into a city and state.",
    useWhen: "Fill city and state after a user enters a ZIP code. lookupPostalCode() calls this endpoint.",
    permissions: ["payers:read"],
    queryFields: [field("postalCode", "string", "US ZIP code. The input is trimmed and the first five characters are used, including for ZIP+4 input.", true)],
    responseFields: [field("postalCode", "string", "Normalized five-digit ZIP code. No data wrapper."), field("city", "string", "City name."), field("state", "string", "Two-letter state code.")],
    examples: example("postal-codes?postalCode=94105"),
    responseExample: json({ postalCode: "94105", city: "San Francisco", state: "CA" }),
    notes: [...browserNotes, { title: "Lookup errors", body: 'Invalid input returns HTTP 400 with { "error": "invalid zip" }. An unknown ZIP code returns HTTP 404 with { "error": "not found" }.' }],
  },
  {
    slug: "delivery-preview", group: "Directories", method: "GET",
    path: "/browser/delivery-preview", authentication: "browser-session",
    title: "Preview bill delivery",
    summary: "Read delivery choices and a recommended route before submitting a bill.",
    useWhen: "Show routing choices after the user selects a claims administrator and payer. getDeliveryPreview() calls this endpoint. For an existing bill, getDeliveryOptions() uses /browser/bills/{billId}/delivery-options with bills:read instead.",
    permissions: ["payers:read"],
    queryFields: [field("claimsAdministratorId", "string", "Selected claims-administrator directory id.", true), field("payerId", "string", "Selected payer-choice key from the search response's payers[].key."), field("injuryState", "string", "Two-letter state code; default CA.")],
    responseFields: [
      field("payerName", "string", "Resolved payer display name. No data wrapper."),
      field("recommended", "object", "Recommended option, when one is available; has the same shape as options[]."),
      field("options[]", "object[]", "Available submission options. Portal routes are excluded."),
      field("options[].route / label / detail", "string", "Delivery route and display text."),
      field("options[].fallback", "boolean", "Whether this is a fallback option."),
      field("options[].confidence / payerName", "string", "Routing confidence and payer display name."),
      field("options[].target / chKey / payerId", "string", "Optional destination, clearinghouse key, and routing payer ID. Routing payer IDs differ from directory selection keys."),
      field("options[].printAndMail", "boolean", "Optional print-and-mail indicator."),
      field("options[].costUsd", "number", "Optional delivery cost in US dollars."),
      field("contacts", "object", "Optional or nullable faxNumber, claimsEmail, portalUrl, and mailingAddress properties."),
    ],
    examples: example("delivery-preview?claimsAdministratorId=admin_example&payerId=payer_example&injuryState=CA"),
    responseExample: json({ payerName: "Example Insurance", options: [], contacts: { claimsEmail: "billing@example.com" } }),
    notes: [...browserNotes, { title: "Preview is advisory", body: "This endpoint does not submit a bill or guarantee delivery. The final route is resolved during submission. The example shows no available submission option, so recommended is omitted. Missing claimsAdministratorId returns HTTP 400; an unknown administrator returns HTTP 404, using Problem Details." }],
  },
];
